### ISSUE TITLE
Few problems (and solutions) with the systemd scripts on CentOS 7

### ISSUE THREAD

**Issue by kaipila** [error10/bitcoin#5] opened 2015-02-27 11:49 UTC
Hello.

Trying to get the bitcoind to run as a service I ran in to couple of problems, found work arounds and though you should be aware of these. This is all on CentOS 7.

1. PID file

Since the service is ran as the bitcoin user it can't create the PID file under /var/run nor /run. For some reason /etc/sysconfig/bitcoin was referring to /var/run and /usr/lib/systemd/system/bitcoin.service was pointing to /run which was also strange. So, I changed the /etc/sysconfig/bitcoin to:

PID_FILE="/var/lib/bitcoin/bitcoind.pid"

Also, this change had to be represented in /usr/lib/systemd/system/bitcoin.service, so I changed:

PIDFile=/var/lib/bitcoin/bitcoind.pid

2. Error: Specified data directory "$DATA_DIR" does not exist.

Seeing these messages in my /var/log/messages I went ahead and made some additional changes in the /usr/lib/systemd/system/bitcoin.service, namely the ExecStart line I changed to:

ExecStart=/usr/sbin/bitcoind -daemon -conf=${CONFIG_FILE} -datadir=${DATA_DIR} -pid=${PID_FILE} $OPTIONS

After these two changes I got everything running.

**Comment by error10** [comment] 2015-02-27 16:34
Hi,

I'm investigating the missing PID file now. I was able to reproduce this problem on a fresh CentOS 7 system. 

(Note that the path is more-or-less correct; /run is where PID files go. It used to be /var/run and this was moved, but one symlinked to the other.)

I also verified that your change to ExecStart fixes that problem, so I'll be putting that in.

Stay tuned...

**Comment by kaipila** [comment] 2015-02-27 18:57
Hey!

/var/run or /run, in either case the user bitcoin probably does not have
permissions to write to that directory, so that's why I changed the PID
file location to /var/lib/bitcoin, since there the user has privileges.

On Fri, Feb 27, 2015 at 6:34 PM, error10 <notifications@github.com> wrote:

> Hi,
>
> I'm investigating the missing PID file now. I was able to reproduce this
> problem on a fresh CentOS 7 system.
>
> (Note that the path is more-or-less correct; /run is where PID files go.
> It used to be /var/run and this was moved, but one symlinked to the other.)
>
> I also verified that your change to ExecStart fixes that problem, so I'll
> be putting that in.
>
> Stay tuned...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/error10/bitcoin/issues/5#issuecomment-76424349>.
>



-- 
Antti Kaipila
Skype: Kaipila

**Comment by error10** [comment] 2015-02-27 19:19
Hi again,

My aim with this repo is to produce packages that will eventually be able to ship officially as part of the Fedora and Red Hat Enterprise Linux distributions. As such I try to build them in accordance with the distribution [packaging guidelines](http://fedoraproject.org/wiki/Packaging:Guidelines). One of those is that all files must be in [standard locations](http://fedoraproject.org/wiki/Packaging:Guidelines#Filesystem_Layout).

It was easy enough to fix the problem with the PID file, as it turns out systemd will create a directory under /run for bitcoind to use and give it the proper permissions. This is working its way through the build server now, and will be released as 0.10.0-2 later tonight.

**Comment by kaipila** [comment] 2015-02-28 10:45
Here we go

https://www.youtube.com/watch?v=auDmlbaH590

On Fri, Feb 27, 2015 at 9:19 PM, error10 <notifications@github.com> wrote:

> Hi again,
>
> My aim with this repo is to produce packages that will eventually be able
> to ship officially as part of the Fedora and Red Hat Enterprise Linux
> distributions. As such I try to build them in accordance with the
> distribution packaging guidelines
> <http://fedoraproject.org/wiki/Packaging:Guidelines>. One of those is
> that all files must be in standard locations
> <http://fedoraproject.org/wiki/Packaging:Guidelines#Filesystem_Layout>.
>
> It was easy enough to fix the problem with the PID file, as it turns out
> systemd will create a directory under /run for bitcoind to use and give it
> the proper permissions. This is working its way through the build server
> now, and will be released as 0.10.0-2 later tonight.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/error10/bitcoin/issues/5#issuecomment-76454564>.
>



-- 
Antti Kaipila
Skype: Kaipila

**Comment by error10** [comment] 2015-02-28 14:49
0.10.0-3 has been pushed to the repositories and addresses both issues reported here.

Note that PID_FILE has been removed as a configurable option; if you really need to edit this (you should not) then edit a copy of the unit file.

**Closed by error10** 2015-02-28 14:49 UTC
